basePath: /
host: https://poker-tt7i.onrender.com
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a poker server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Card House API
  version: "1.0"
paths: {}
swagger: "2.0"
